#!/usr/bin/env python3
"""
Train PocketMon-backbone pretraining model on processed apo-holo pair graphs.

Expected input graph files are generated by build_pyg_graphs.py and contain:
  - apo_pos: (N, 3)
  - holo_pos: (N, 3)
  - apo_backbone: (N, 4, 3), atom order N/CA/C/O
  - holo_backbone: (N, 4, 3), atom order N/CA/C/O
  - apo_backbone_mask: (N, 4)
  - holo_backbone_mask: (N, 4)
  - edge_index: (2, E)
  - edge_label: (E,)
  - sequence: (N,)
"""

from __future__ import annotations

import argparse
import contextlib
import json
import logging
import random
import time
from pathlib import Path
from typing import Dict, Iterable, List, Sequence, Tuple

import torch
import torch.nn.functional as F
from torch import Tensor
from torch.optim import AdamW
from torch.utils.data import Dataset, Subset
from torch_geometric.data import Data
from torch_geometric.loader import DataLoader

from model import EdgeGCLConfig, EdgeGCLModel


DEFAULT_DATA_DIR = "data/processed_pairs_backbone"
REQUIRED_GRAPH_ATTRS = ("apo_pos", "holo_pos", "edge_index", "edge_label", "sequence")


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Pretrain PocketMon backbone on apo-holo pair graphs")

    # Data
    p.add_argument("--data-dir", type=str, default=DEFAULT_DATA_DIR)
    p.add_argument(
        "--validate-first-n",
        type=int,
        default=32,
        help="Validate the first N graph files before training; set 0 to disable.",
    )
    p.add_argument("--batch-size", type=int, default=8)
    p.add_argument("--num-workers", type=int, default=4)
    p.add_argument("--val-ratio", type=float, default=0.05)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--max-samples", type=int, default=0, help="Debug only: use first N samples")

    # Optimization
    p.add_argument("--epochs", type=int, default=24)
    p.add_argument("--lr", type=float, default=2e-5)
    p.add_argument("--weight-decay", type=float, default=1e-5)
    p.add_argument("--grad-clip", type=float, default=1.0)
    p.add_argument("--amp", action="store_true", help="Enable mixed precision if CUDA is available")
    p.add_argument("--edge-pos-weight", type=float, default=1.0, help="BCE pos_weight for edge labels")
    p.add_argument("--lambda-contrastive", type=float, default=1.0)
    p.add_argument("--lambda-edge", type=float, default=1.0)
    p.add_argument("--lambda-ranking", type=float, default=0.0)
    p.add_argument("--lambda-pseudo", type=float, default=0.0)
    p.add_argument(
        "--contrastive-variant",
        type=str,
        default="all_nodes",
        choices=["all_nodes", "sampled_apo_holo"],
        help="all_nodes keeps the historical full-node InfoNCE; sampled_apo_holo uses filtered residue pairs.",
    )
    p.add_argument(
        "--contrastive-samples-per-graph",
        type=int,
        default=96,
        help="Residues sampled per graph for sampled_apo_holo contrastive loss.",
    )
    p.add_argument(
        "--contrastive-max-ca-displacement",
        type=float,
        default=8.0,
        help="Drop apo/holo positive residue pairs whose CA displacement exceeds this Angstrom cutoff.",
    )
    p.add_argument(
        "--contrastive-stable-ca-displacement",
        type=float,
        default=0.0,
        help=(
            "When >0, use this stricter Angstrom cutoff for apo/holo positives. "
            "This preserves stable-residue invariance without forcing mobile residues together."
        ),
    )
    p.add_argument(
        "--contrastive-local-change-cutoff",
        type=float,
        default=0.0,
        help=(
            "Optional mean local distance-map change cutoff in Angstrom for positives; "
            "0 disables this extra filter."
        ),
    )
    p.add_argument(
        "--contrastive-local-neighbor-cutoff",
        type=float,
        default=8.0,
        help="Apo CA neighbor cutoff in Angstrom used by the local distance-map change filter.",
    )
    p.add_argument(
        "--contrastive-local-min-neighbors",
        type=int,
        default=2,
        help="Minimum apo local neighbors required when local distance-map change filtering is enabled.",
    )
    p.add_argument(
        "--contrastive-negatives",
        type=str,
        default="other_protein",
        choices=["other_protein", "batch_all", "other_protein_far_same_protein"],
        help=(
            "Negative pool for sampled_apo_holo. other_protein masks same-protein off-diagonal residues; "
            "other_protein_far_same_protein adds same-protein residues that are distant in sequence and space."
        ),
    )
    p.add_argument(
        "--contrastive-same-protein-seq-gap",
        type=int,
        default=24,
        help="Minimum sequence-index gap for same-protein far negatives.",
    )
    p.add_argument(
        "--contrastive-same-protein-ca-cutoff",
        type=float,
        default=12.0,
        help="Minimum apo CA distance in Angstrom for same-protein far negatives.",
    )
    p.add_argument("--pseudo-pos-weight", type=float, default=4.0)
    p.add_argument("--pseudo-neighbor-cutoff", type=float, default=8.0)
    p.add_argument("--pseudo-positive-frac", type=float, default=0.2)
    p.add_argument("--pseudo-negative-frac", type=float, default=0.5)
    p.add_argument("--pseudo-density-weight", type=float, default=2.0)
    p.add_argument("--ranking-margin-delta", type=float, default=1.0)
    p.add_argument("--ranking-margin-score", type=float, default=0.2)
    p.add_argument("--ranking-max-pairs", type=int, default=4096)

    # Model config overrides
    p.add_argument("--num-layers", type=int, default=4)
    p.add_argument("--scalar-channels", type=int, default=128)
    p.add_argument("--vector-channels", type=int, default=16)
    p.add_argument("--tensor-channels", type=int, default=0)
    p.add_argument("--edge-dim", type=int, default=64)
    p.add_argument("--radial-hidden-dim", type=int, default=128)
    p.add_argument("--edge-hidden-dim", type=int, default=256)
    p.add_argument("--dropout", type=float, default=0.1)
    p.add_argument("--temperature", type=float, default=0.1)
    p.add_argument("--contrastive-proj-dim", type=int, default=128)
    p.add_argument("--cutoff", type=float, default=1.5)
    p.add_argument("--n-rbf", type=int, default=32)
    p.add_argument("--n-pos-enc", type=int, default=16)
    p.add_argument("--num-heads", type=int, default=4)
    p.add_argument("--lmax", type=int, default=2)
    p.add_argument("--max-num-neighbors", type=int, default=128)
    p.add_argument("--cls-hidden-dim", type=int, default=256)
    p.add_argument("--edge-updates", action=argparse.BooleanOptionalAction, default=False)

    # Runtime/checkpoint
    p.add_argument("--device", type=str, default="auto", choices=["auto", "cpu", "cuda"])
    p.add_argument("--save-dir", type=str, default="checkpoints_pretrain")
    p.add_argument("--save-every", type=int, default=1)
    p.add_argument("--resume", type=str, default="", help="Path to checkpoint to resume from")

    return p.parse_args()


def setup_logging(save_dir: Path) -> None:
    save_dir.mkdir(parents=True, exist_ok=True)
    log_path = save_dir / "train.log"
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        handlers=[
            logging.FileHandler(log_path, mode="a", encoding="utf-8"),
            logging.StreamHandler(),
        ],
    )


def set_seed(seed: int) -> None:
    random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def select_device(device_arg: str) -> torch.device:
    if device_arg == "cpu":
        return torch.device("cpu")
    if device_arg == "cuda":
        if not torch.cuda.is_available():
            raise RuntimeError("CUDA requested but not available")
        return torch.device("cuda")
    return torch.device("cuda" if torch.cuda.is_available() else "cpu")


def safe_to_device(data: Data, device: torch.device) -> Data:
    # PyG Data.to handles Tensor attrs and keeps non-Tensor attrs intact.
    return data.to(device)


def build_model_from_args(args: argparse.Namespace) -> EdgeGCLModel:
    cfg = EdgeGCLConfig(
        num_layers=args.num_layers,
        scalar_channels=args.scalar_channels,
        vector_channels=args.vector_channels,
        tensor_channels=args.tensor_channels,
        edge_dim=args.edge_dim,
        radial_hidden_dim=args.radial_hidden_dim,
        edge_hidden_dim=args.edge_hidden_dim,
        dropout=args.dropout,
        temperature=args.temperature,
        contrastive_proj_dim=args.contrastive_proj_dim,
        cutoff=args.cutoff,
        n_rbf=args.n_rbf,
        n_pos_enc=args.n_pos_enc,
        num_heads=args.num_heads,
        lmax=args.lmax,
        max_num_neighbors=args.max_num_neighbors,
        cls_hidden_dim=args.cls_hidden_dim,
        edge_updates=args.edge_updates,
    )
    return EdgeGCLModel(cfg)


def list_pt_files(data_dir: Path) -> List[Path]:
    data_dir = data_dir.expanduser().resolve()
    files = sorted(data_dir.glob("*.pt"))
    if not files:
        raise FileNotFoundError(f"No .pt files found under: {data_dir}")
    return files


def load_graph_file(path: Path) -> Data:
    try:
        data = torch.load(path, map_location="cpu", weights_only=False)
    except TypeError:
        # For older torch versions without weights_only argument.
        data = torch.load(path, map_location="cpu")
    if not isinstance(data, Data):
        raise TypeError(f"{path} does not contain a torch_geometric.data.Data object")
    return normalize_graph(data, path)


def normalize_graph(data: Data, path: Path) -> Data:
    missing = [name for name in REQUIRED_GRAPH_ATTRS if not hasattr(data, name)]
    if missing:
        raise ValueError(f"{path} missing required fields: {missing}")

    data.apo_pos = data.apo_pos.float()
    data.holo_pos = data.holo_pos.float()
    data.edge_index = data.edge_index.long()
    data.edge_label = data.edge_label.long().view(-1)
    data.sequence = data.sequence.long().view(-1)
    if hasattr(data, "apo_backbone"):
        data.apo_backbone = data.apo_backbone.float()
    if hasattr(data, "holo_backbone"):
        data.holo_backbone = data.holo_backbone.float()
    if hasattr(data, "apo_backbone_mask"):
        data.apo_backbone_mask = data.apo_backbone_mask.bool()
    if hasattr(data, "holo_backbone_mask"):
        data.holo_backbone_mask = data.holo_backbone_mask.bool()

    n = int(data.sequence.numel())
    if data.apo_pos.dim() != 2 or data.apo_pos.size(-1) != 3:
        raise ValueError(f"{path} apo_pos must have shape (N, 3), got {tuple(data.apo_pos.shape)}")
    if data.holo_pos.dim() != 2 or data.holo_pos.size(-1) != 3:
        raise ValueError(f"{path} holo_pos must have shape (N, 3), got {tuple(data.holo_pos.shape)}")
    if data.apo_pos.size(0) != n or data.holo_pos.size(0) != n:
        raise ValueError(
            f"{path} node count mismatch: sequence={n}, "
            f"apo_pos={data.apo_pos.size(0)}, holo_pos={data.holo_pos.size(0)}"
        )
    for attr in ("apo_backbone", "holo_backbone"):
        if hasattr(data, attr):
            value = getattr(data, attr)
            if value.dim() != 3 or value.size(0) != n or value.size(1) < 3 or value.size(2) != 3:
                raise ValueError(f"{path} {attr} must have shape (N, >=3, 3), got {tuple(value.shape)}")
    for attr in ("apo_backbone_mask", "holo_backbone_mask"):
        if hasattr(data, attr):
            value = getattr(data, attr)
            if value.dim() != 2 or value.size(0) != n or value.size(1) < 3:
                raise ValueError(f"{path} {attr} must have shape (N, >=3), got {tuple(value.shape)}")
    if data.edge_index.dim() != 2 or data.edge_index.size(0) != 2:
        raise ValueError(f"{path} edge_index must have shape (2, E), got {tuple(data.edge_index.shape)}")
    if data.edge_label.numel() != data.edge_index.size(1):
        raise ValueError(
            f"{path} edge_label length {data.edge_label.numel()} does not match "
            f"edge count {data.edge_index.size(1)}"
        )
    if data.edge_index.numel() > 0:
        min_idx = int(data.edge_index.min().item())
        max_idx = int(data.edge_index.max().item())
        if min_idx < 0 or max_idx >= n:
            raise ValueError(f"{path} edge_index out of range for {n} nodes: min={min_idx}, max={max_idx}")

    # Required for PyG batching because these graphs use apo_pos/holo_pos instead
    # of standard x/pos fields. Without it, isolated nodes can make edge offsets
    # incorrect in batched edge_index tensors.
    data.num_nodes = n
    return data


def validate_graph_files(files: Sequence[Path], limit: int) -> None:
    if limit <= 0:
        return
    for path in files[: min(limit, len(files))]:
        load_graph_file(path)


class PTGraphDataset(Dataset):
    def __init__(self, files: List[Path]) -> None:
        self.files = files

    def __len__(self) -> int:
        return len(self.files)

    def __getitem__(self, idx: int) -> Data:
        return load_graph_file(self.files[idx])


def split_indices(n: int, val_ratio: float, seed: int) -> Tuple[List[int], List[int]]:
    indices = list(range(n))
    rng = random.Random(seed)
    rng.shuffle(indices)

    n_val = int(round(n * val_ratio))
    n_val = max(1, min(n - 1, n_val)) if n > 1 else 0
    val_idx = indices[:n_val]
    train_idx = indices[n_val:]
    return train_idx, val_idx


def save_json(path: Path, payload: Dict) -> None:
    with path.open("w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)


def binary_auc_torch(y_true: Tensor, y_score: Tensor) -> float:
    """
    Compute ROC-AUC in pure torch (CPU) to avoid external deps.
    Returns NaN when only one class is present.
    """
    y_true = y_true.detach().float().cpu().view(-1)
    y_score = y_score.detach().float().cpu().view(-1)

    pos = (y_true == 1).sum().item()
    neg = (y_true == 0).sum().item()
    if pos == 0 or neg == 0:
        return float("nan")

    order = torch.argsort(y_score, descending=False)
    ranks = torch.empty_like(order, dtype=torch.float32)
    ranks[order] = torch.arange(1, len(y_score) + 1, dtype=torch.float32)
    rank_sum_pos = ranks[y_true == 1].sum().item()
    auc = (rank_sum_pos - pos * (pos + 1) / 2.0) / (pos * neg)
    return float(auc)


def edge_loss_with_empty_support(
    edge_logits: Tensor,
    edge_label: Tensor,
    pos_weight: Tensor,
) -> Tuple[Tensor, int]:
    if edge_label.numel() == 0:
        return edge_logits.new_zeros(()), 0
    loss = F.binary_cross_entropy_with_logits(
        edge_logits,
        edge_label.float(),
        pos_weight=pos_weight,
    )
    return loss, int(edge_label.numel())


def sampled_apo_holo_contrastive_loss(
    model: EdgeGCLModel,
    z_apo: Tensor,
    z_holo: Tensor,
    apo_pos: Tensor,
    holo_pos: Tensor,
    batch: Tensor,
    args: argparse.Namespace,
) -> Tuple[Tensor, Dict[str, float]]:
    """Symmetric residue-level apo/holo InfoNCE with per-protein sampling.

    Positive pairs are matched residues from the same apo-holo graph. By
    default, off-diagonal residues from the same protein are masked out. The
    v2 negative option also admits same-protein residues that are far in both
    sequence index and apo CA space, which discourages broad false positives.
    """
    sample_indices: List[Tensor] = []
    sample_graph_ids: List[Tensor] = []
    displacement = (apo_pos - holo_pos).norm(dim=-1)
    positive_cutoff = float(args.contrastive_max_ca_displacement)
    stable_cutoff = float(getattr(args, "contrastive_stable_ca_displacement", 0.0))
    if stable_cutoff > 0:
        positive_cutoff = min(positive_cutoff, stable_cutoff)

    for graph_id in torch.unique(batch):
        graph_mask = batch == graph_id
        eligible_mask = graph_mask & (displacement <= positive_cutoff)

        local_change_cutoff = float(getattr(args, "contrastive_local_change_cutoff", 0.0))
        if local_change_cutoff > 0 and bool(eligible_mask.any()):
            graph_idx = torch.nonzero(graph_mask, as_tuple=False).view(-1)
            apo = apo_pos[graph_idx]
            holo = holo_pos[graph_idx]
            if graph_idx.numel() > 1:
                d_apo = torch.cdist(apo, apo)
                d_holo = torch.cdist(holo, holo)
                not_self = ~torch.eye(graph_idx.numel(), device=apo_pos.device, dtype=torch.bool)
                local_neighbors = (d_apo < float(args.contrastive_local_neighbor_cutoff)) & not_self
                local_neighbor_count = local_neighbors.sum(dim=1)
                local_change = ((d_holo - d_apo).abs() * local_neighbors.to(apo_pos.dtype)).sum(dim=1)
                local_change = local_change / local_neighbor_count.clamp(min=1).to(apo_pos.dtype)
                has_enough_neighbors = local_neighbor_count >= int(args.contrastive_local_min_neighbors)
                local_mask = torch.zeros_like(graph_mask)
                local_mask[graph_idx] = (local_change <= local_change_cutoff) & has_enough_neighbors
                eligible_mask = eligible_mask & local_mask

        eligible = torch.nonzero(eligible_mask, as_tuple=False).view(-1)
        if eligible.numel() == 0:
            continue
        max_samples = int(args.contrastive_samples_per_graph)
        if max_samples > 0 and eligible.numel() > max_samples:
            perm = torch.randperm(eligible.numel(), device=eligible.device)[:max_samples]
            eligible = eligible[perm]
        sample_indices.append(eligible)
        sample_graph_ids.append(torch.full_like(eligible, int(graph_id.item())))

    if len(sample_indices) < 2:
        zero = (z_apo.sum() + z_holo.sum()) * 0.0
        return zero, {
            "contrastive_count": 0.0,
            "contrastive_acc": float("nan"),
            "contrastive_pos_sim": float("nan"),
            "contrastive_neg_per_anchor": 0.0,
        }

    idx = torch.cat(sample_indices, dim=0)
    graph_ids = torch.cat(sample_graph_ids, dim=0)
    if idx.numel() < 2 or torch.unique(graph_ids).numel() < 2:
        zero = (z_apo.sum() + z_holo.sum()) * 0.0
        return zero, {
            "contrastive_count": 0.0,
            "contrastive_acc": float("nan"),
            "contrastive_pos_sim": float("nan"),
            "contrastive_neg_per_anchor": 0.0,
        }

    q = F.normalize(model.contrastive_head.projector(z_apo[idx]), dim=-1)
    k = F.normalize(model.contrastive_head.projector(z_holo[idx]), dim=-1)
    logits = q @ k.t() / float(model.contrastive_head.temperature)
    labels = torch.arange(logits.size(0), device=logits.device)

    if args.contrastive_negatives in {"other_protein", "other_protein_far_same_protein"}:
        same_graph = graph_ids[:, None] == graph_ids[None, :]
        diagonal = torch.eye(logits.size(0), device=logits.device, dtype=torch.bool)
        allowed = (~same_graph) | diagonal
        if args.contrastive_negatives == "other_protein_far_same_protein":
            seq_gap = torch.abs(idx[:, None] - idx[None, :]) > int(args.contrastive_same_protein_seq_gap)
            ca_dist = torch.cdist(apo_pos[idx], apo_pos[idx]) > float(args.contrastive_same_protein_ca_cutoff)
            allowed = allowed | (same_graph & seq_gap & ca_dist)
        logits_ab = logits.masked_fill(~allowed, -1.0e9)
        logits_ba = logits.t().masked_fill(~allowed.t(), -1.0e9)
        neg_per_anchor = (allowed.sum(dim=1).float() - 1.0).mean()
    else:
        logits_ab = logits
        logits_ba = logits.t()
        neg_per_anchor = logits.new_tensor(float(max(0, logits.size(0) - 1)))

    loss_ab = F.cross_entropy(logits_ab, labels)
    loss_ba = F.cross_entropy(logits_ba, labels)
    loss = 0.5 * (loss_ab + loss_ba)
    acc_ab = (logits_ab.argmax(dim=1) == labels).float().mean()
    acc_ba = (logits_ba.argmax(dim=1) == labels).float().mean()
    pos_sim = torch.diagonal(q @ k.t()).mean()
    return loss, {
        "contrastive_count": float(idx.numel()),
        "contrastive_acc": float((0.5 * (acc_ab + acc_ba)).item()),
        "contrastive_pos_sim": float(pos_sim.item()),
        "contrastive_neg_per_anchor": float(neg_per_anchor.item()),
    }


def build_pseudo_pocket_targets(
    apo_pos: Tensor,
    holo_pos: Tensor,
    batch: Tensor,
    neighbor_cutoff: float,
    positive_frac: float,
    negative_frac: float,
    density_weight: float,
) -> Tuple[Tensor, Tensor, Tensor]:
    labels = apo_pos.new_zeros((apo_pos.size(0),))
    mask = torch.zeros((apo_pos.size(0),), device=apo_pos.device, dtype=torch.bool)
    score = apo_pos.new_zeros((apo_pos.size(0),))

    for graph_id in torch.unique(batch):
        idx = torch.nonzero(batch == graph_id, as_tuple=False).view(-1)
        n = int(idx.numel())
        if n < 3:
            continue

        apo = apo_pos[idx]
        holo = holo_pos[idx]
        d_apo = torch.cdist(apo, apo)
        d_holo = torch.cdist(holo, holo)
        not_self = ~torch.eye(n, device=apo_pos.device, dtype=torch.bool)
        neigh_apo = (d_apo < float(neighbor_cutoff)) & not_self
        neigh_holo = (d_holo < float(neighbor_cutoff)) & not_self

        apo_count = neigh_apo.sum(dim=1).clamp(min=1).to(apo_pos.dtype)
        expansion = (d_holo - d_apo).clamp(min=0.0)
        mean_expansion = (expansion * neigh_apo.to(expansion.dtype)).sum(dim=1) / apo_count
        density_drop = (neigh_apo.sum(dim=1) - neigh_holo.sum(dim=1)).clamp(min=0).to(apo_pos.dtype) / apo_count
        graph_score = mean_expansion + float(density_weight) * density_drop
        score[idx] = graph_score

        order = torch.argsort(graph_score, descending=True)
        k_pos = max(1, int(round(n * float(positive_frac))))
        k_neg = max(1, int(round(n * float(negative_frac))))
        k_pos = min(k_pos, n)
        k_neg = min(k_neg, max(0, n - k_pos))
        if k_neg == 0:
            continue

        pos_idx = idx[order[:k_pos]]
        neg_idx = idx[order[-k_neg:]]
        labels[pos_idx] = 1.0
        mask[pos_idx] = True
        mask[neg_idx] = True

    return labels, mask, score


def pseudo_pocket_loss(
    pseudo_logits: Tensor,
    apo_pos: Tensor,
    holo_pos: Tensor,
    batch: Tensor,
    args: argparse.Namespace,
) -> Tuple[Tensor, Dict[str, float]]:
    labels, mask, score = build_pseudo_pocket_targets(
        apo_pos=apo_pos,
        holo_pos=holo_pos,
        batch=batch,
        neighbor_cutoff=args.pseudo_neighbor_cutoff,
        positive_frac=args.pseudo_positive_frac,
        negative_frac=args.pseudo_negative_frac,
        density_weight=args.pseudo_density_weight,
    )
    if not bool(mask.any()):
        return pseudo_logits.new_zeros(()), {
            "pseudo_count": 0.0,
            "pseudo_pos": 0.0,
            "pseudo_acc": float("nan"),
            "pseudo_auc": float("nan"),
            "opening_score": 0.0,
        }

    pos_weight = torch.tensor([args.pseudo_pos_weight], device=pseudo_logits.device, dtype=torch.float32)
    loss = F.binary_cross_entropy_with_logits(
        pseudo_logits[mask],
        labels[mask],
        pos_weight=pos_weight,
    )
    prob = torch.sigmoid(pseudo_logits[mask])
    pred = (prob >= 0.5).to(labels.dtype)
    acc = float((pred == labels[mask]).float().mean().item())
    auc = binary_auc_torch(labels[mask].detach().cpu(), prob.detach().cpu())
    return loss, {
        "pseudo_count": float(mask.sum().item()),
        "pseudo_pos": float(labels[mask].sum().item()),
        "pseudo_acc": acc,
        "pseudo_auc": auc,
        "opening_score": float(score[mask].mean().item()),
    }


def edge_delta_ranking_loss(
    edge_scores: Tensor,
    apo_pos: Tensor,
    holo_pos: Tensor,
    edge_index: Tensor,
    margin_delta: float,
    margin_score: float,
    max_pairs: int,
) -> Tuple[Tensor, int]:
    if edge_scores.numel() < 2 or edge_index.numel() == 0 or max_pairs <= 0:
        return edge_scores.new_zeros(()), 0

    src, dst = edge_index
    apo_dist = (apo_pos[src] - apo_pos[dst]).norm(dim=-1)
    holo_dist = (holo_pos[src] - holo_pos[dst]).norm(dim=-1)
    delta_mag = (holo_dist - apo_dist).abs()

    n_edges = int(edge_scores.numel())
    n_pairs = min(int(max_pairs), n_edges * max(1, n_edges - 1))
    idx_a = torch.randint(n_edges, (n_pairs,), device=edge_scores.device)
    idx_b = torch.randint(n_edges, (n_pairs,), device=edge_scores.device)
    valid = idx_a != idx_b
    idx_a = idx_a[valid]
    idx_b = idx_b[valid]
    if idx_a.numel() == 0:
        return edge_scores.new_zeros(()), 0

    delta_diff = delta_mag[idx_a] - delta_mag[idx_b]
    valid = delta_diff.abs() > float(margin_delta)
    if not bool(valid.any()):
        return edge_scores.new_zeros(()), 0

    idx_a = idx_a[valid]
    idx_b = idx_b[valid]
    delta_diff = delta_diff[valid]
    high_idx = torch.where(delta_diff > 0, idx_a, idx_b)
    low_idx = torch.where(delta_diff > 0, idx_b, idx_a)
    score_gap = edge_scores[high_idx] - edge_scores[low_idx]
    loss = F.relu(float(margin_score) - score_gap).mean()
    return loss, int(score_gap.numel())


def train_one_epoch(
    model: EdgeGCLModel,
    loader: Iterable[Data],
    optimizer: torch.optim.Optimizer,
    scaler: torch.cuda.amp.GradScaler | None,
    device: torch.device,
    args: argparse.Namespace,
) -> Dict[str, float]:
    model.train()

    total = 0
    total_loss = 0.0
    total_contrastive = 0.0
    total_edge = 0.0
    total_ranking = 0.0
    total_pseudo = 0.0
    total_contrastive_acc = 0.0
    total_contrastive_pos_sim = 0.0
    total_contrastive_neg_per_anchor = 0.0
    total_pseudo_acc = 0.0
    total_pseudo_auc = 0.0
    total_opening_score = 0.0
    contrastive_count = 0.0
    edge_count = 0
    ranking_count = 0
    pseudo_count = 0.0
    pseudo_pos = 0.0
    correct = 0

    pos_weight = torch.tensor([args.edge_pos_weight], device=device, dtype=torch.float32)

    for batch in loader:
        batch = safe_to_device(batch, device)
        optimizer.zero_grad(set_to_none=True)

        use_amp = scaler is not None and device.type == "cuda"
        amp_ctx = torch.cuda.amp.autocast(dtype=torch.float16) if use_amp else contextlib.nullcontext()
        with amp_ctx:
            loss_pseudo = batch.apo_pos.new_zeros(())
            pseudo_m = {
                "pseudo_count": 0.0,
                "pseudo_pos": 0.0,
                "pseudo_acc": float("nan"),
                "pseudo_auc": float("nan"),
                "opening_score": 0.0,
            }
            contrastive_m = {
                "contrastive_count": 0.0,
                "contrastive_acc": float("nan"),
                "contrastive_pos_sim": float("nan"),
                "contrastive_neg_per_anchor": 0.0,
            }
            if args.lambda_pseudo > 0:
                pseudo_logits, edge_logits = model.forward_pseudo(
                    apo_pos=batch.apo_pos,
                    sequence=batch.sequence,
                    batch=batch.batch,
                    apo_backbone=getattr(batch, "apo_backbone", None),
                    apo_backbone_mask=getattr(batch, "apo_backbone_mask", None),
                    edge_index=batch.edge_index,
                    compute_edge=(args.lambda_edge > 0 or args.lambda_ranking > 0),
                )
                loss_contrastive = edge_logits.new_zeros(())
                loss_pseudo, pseudo_m = pseudo_pocket_loss(
                    pseudo_logits=pseudo_logits,
                    apo_pos=batch.apo_pos,
                    holo_pos=batch.holo_pos,
                    batch=batch.batch,
                    args=args,
                )
            else:
                if args.lambda_contrastive > 0 and args.contrastive_variant == "sampled_apo_holo":
                    out = model(
                        apo_pos=batch.apo_pos,
                        holo_pos=batch.holo_pos,
                        edge_index=batch.edge_index,
                        sequence=batch.sequence,
                        batch=batch.batch,
                        apo_backbone=getattr(batch, "apo_backbone", None),
                        holo_backbone=getattr(batch, "holo_backbone", None),
                        apo_backbone_mask=getattr(batch, "apo_backbone_mask", None),
                        holo_backbone_mask=getattr(batch, "holo_backbone_mask", None),
                    )
                    loss_contrastive, contrastive_m = sampled_apo_holo_contrastive_loss(
                        model=model,
                        z_apo=out["z_apo"],
                        z_holo=out["z_holo"],
                        apo_pos=batch.apo_pos,
                        holo_pos=batch.holo_pos,
                        batch=batch.batch,
                        args=args,
                    )
                    edge_logits = out["edge_logits"]
                else:
                    loss_contrastive, edge_logits = model.forward_train(
                        apo_pos=batch.apo_pos,
                        holo_pos=batch.holo_pos,
                        edge_index=batch.edge_index,
                        sequence=batch.sequence,
                        batch=batch.batch,
                        apo_backbone=getattr(batch, "apo_backbone", None),
                        holo_backbone=getattr(batch, "holo_backbone", None),
                        apo_backbone_mask=getattr(batch, "apo_backbone_mask", None),
                        holo_backbone_mask=getattr(batch, "holo_backbone_mask", None),
                        compute_contrastive=args.lambda_contrastive > 0,
                    )
            if args.lambda_edge > 0 or args.lambda_ranking > 0:
                loss_edge, this_edge_count = edge_loss_with_empty_support(
                    edge_logits=edge_logits,
                    edge_label=batch.edge_label,
                    pos_weight=pos_weight,
                )
            else:
                loss_edge = batch.apo_pos.new_zeros(())
                this_edge_count = 0
            if args.lambda_ranking > 0:
                loss_ranking, this_ranking_count = edge_delta_ranking_loss(
                    edge_scores=edge_logits,
                    apo_pos=batch.apo_pos,
                    holo_pos=batch.holo_pos,
                    edge_index=batch.edge_index,
                    margin_delta=args.ranking_margin_delta,
                    margin_score=args.ranking_margin_score,
                    max_pairs=args.ranking_max_pairs,
                )
            else:
                loss_ranking = edge_logits.new_zeros(())
                this_ranking_count = 0
            loss = (
                args.lambda_contrastive * loss_contrastive
                + args.lambda_edge * loss_edge
                + args.lambda_ranking * loss_ranking
                + args.lambda_pseudo * loss_pseudo
            )

        if use_amp:
            assert scaler is not None
            scaler.scale(loss).backward()
            if args.grad_clip > 0:
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), args.grad_clip)
            scaler.step(optimizer)
            scaler.update()
        else:
            loss.backward()
            if args.grad_clip > 0:
                torch.nn.utils.clip_grad_norm_(model.parameters(), args.grad_clip)
            optimizer.step()

        batch_size_graph = int(batch.num_graphs)
        total += batch_size_graph
        total_loss += float(loss.item()) * batch_size_graph
        total_contrastive += float(loss_contrastive.item()) * batch_size_graph
        total_edge += float(loss_edge.item()) * batch_size_graph
        total_ranking += float(loss_ranking.item()) * batch_size_graph
        total_pseudo += float(loss_pseudo.item()) * batch_size_graph
        contrastive_count += contrastive_m["contrastive_count"]
        if contrastive_m["contrastive_count"] > 0:
            total_contrastive_acc += contrastive_m["contrastive_acc"] * batch_size_graph
            total_contrastive_pos_sim += contrastive_m["contrastive_pos_sim"] * batch_size_graph
            total_contrastive_neg_per_anchor += contrastive_m["contrastive_neg_per_anchor"] * batch_size_graph
        ranking_count += this_ranking_count
        pseudo_count += pseudo_m["pseudo_count"]
        pseudo_pos += pseudo_m["pseudo_pos"]
        if pseudo_m["pseudo_count"] > 0:
            total_pseudo_acc += pseudo_m["pseudo_acc"] * batch_size_graph
            if pseudo_m["pseudo_auc"] == pseudo_m["pseudo_auc"]:
                total_pseudo_auc += pseudo_m["pseudo_auc"] * batch_size_graph
            total_opening_score += pseudo_m["opening_score"] * batch_size_graph

        if this_edge_count > 0:
            preds = (torch.sigmoid(edge_logits) >= 0.5).long()
            correct += int((preds == batch.edge_label.long()).sum().item())
            edge_count += this_edge_count

    metrics = {
        "loss": total_loss / max(1, total),
        "loss_contrastive": total_contrastive / max(1, total),
        "loss_edge": total_edge / max(1, total),
        "loss_ranking": total_ranking / max(1, total),
        "loss_pseudo": total_pseudo / max(1, total),
        "contrastive_count": float(contrastive_count),
        "contrastive_acc": total_contrastive_acc / max(1, total),
        "contrastive_pos_sim": total_contrastive_pos_sim / max(1, total),
        "contrastive_neg_per_anchor": total_contrastive_neg_per_anchor / max(1, total),
        "edge_acc": (correct / edge_count) if edge_count > 0 else float("nan"),
        "edge_count": float(edge_count),
        "ranking_count": float(ranking_count),
        "pseudo_count": float(pseudo_count),
        "pseudo_pos_frac": float(pseudo_pos / max(1.0, pseudo_count)),
        "pseudo_acc": total_pseudo_acc / max(1, total),
        "pseudo_auc": total_pseudo_auc / max(1, total),
        "opening_score": total_opening_score / max(1, total),
    }
    return metrics


@torch.no_grad()
def evaluate(
    model: EdgeGCLModel,
    loader: Iterable[Data],
    device: torch.device,
    args: argparse.Namespace,
) -> Dict[str, float]:
    model.eval()

    total = 0
    total_loss = 0.0
    total_contrastive = 0.0
    total_edge = 0.0
    total_ranking = 0.0
    total_pseudo = 0.0
    total_contrastive_acc = 0.0
    total_contrastive_pos_sim = 0.0
    total_contrastive_neg_per_anchor = 0.0
    total_pseudo_acc = 0.0
    total_pseudo_auc = 0.0
    total_opening_score = 0.0

    contrastive_count = 0.0
    edge_count = 0
    ranking_count = 0
    pseudo_count = 0.0
    pseudo_pos = 0.0
    correct = 0
    all_scores: List[Tensor] = []
    all_labels: List[Tensor] = []

    pos_weight = torch.tensor([args.edge_pos_weight], device=device, dtype=torch.float32)

    for batch in loader:
        batch = safe_to_device(batch, device)
        loss_pseudo = batch.apo_pos.new_zeros(())
        pseudo_m = {
            "pseudo_count": 0.0,
            "pseudo_pos": 0.0,
            "pseudo_acc": float("nan"),
            "pseudo_auc": float("nan"),
            "opening_score": 0.0,
        }
        contrastive_m = {
            "contrastive_count": 0.0,
            "contrastive_acc": float("nan"),
            "contrastive_pos_sim": float("nan"),
            "contrastive_neg_per_anchor": 0.0,
        }
        if args.lambda_pseudo > 0:
            pseudo_logits, edge_logits = model.forward_pseudo(
                apo_pos=batch.apo_pos,
                sequence=batch.sequence,
                batch=batch.batch,
                apo_backbone=getattr(batch, "apo_backbone", None),
                apo_backbone_mask=getattr(batch, "apo_backbone_mask", None),
                edge_index=batch.edge_index,
                compute_edge=(args.lambda_edge > 0 or args.lambda_ranking > 0),
            )
            loss_contrastive = edge_logits.new_zeros(())
            loss_pseudo, pseudo_m = pseudo_pocket_loss(
                pseudo_logits=pseudo_logits,
                apo_pos=batch.apo_pos,
                holo_pos=batch.holo_pos,
                batch=batch.batch,
                args=args,
            )
        else:
            if args.lambda_contrastive > 0 and args.contrastive_variant == "sampled_apo_holo":
                out = model(
                    apo_pos=batch.apo_pos,
                    holo_pos=batch.holo_pos,
                    edge_index=batch.edge_index,
                    sequence=batch.sequence,
                    batch=batch.batch,
                    apo_backbone=getattr(batch, "apo_backbone", None),
                    holo_backbone=getattr(batch, "holo_backbone", None),
                    apo_backbone_mask=getattr(batch, "apo_backbone_mask", None),
                    holo_backbone_mask=getattr(batch, "holo_backbone_mask", None),
                )
                loss_contrastive, contrastive_m = sampled_apo_holo_contrastive_loss(
                    model=model,
                    z_apo=out["z_apo"],
                    z_holo=out["z_holo"],
                    apo_pos=batch.apo_pos,
                    holo_pos=batch.holo_pos,
                    batch=batch.batch,
                    args=args,
                )
                edge_logits = out["edge_logits"]
            else:
                loss_contrastive, edge_logits = model.forward_train(
                    apo_pos=batch.apo_pos,
                    holo_pos=batch.holo_pos,
                    edge_index=batch.edge_index,
                    sequence=batch.sequence,
                    batch=batch.batch,
                    apo_backbone=getattr(batch, "apo_backbone", None),
                    holo_backbone=getattr(batch, "holo_backbone", None),
                    apo_backbone_mask=getattr(batch, "apo_backbone_mask", None),
                    holo_backbone_mask=getattr(batch, "holo_backbone_mask", None),
                    compute_contrastive=args.lambda_contrastive > 0,
                )
        if args.lambda_edge > 0 or args.lambda_ranking > 0:
            loss_edge, this_edge_count = edge_loss_with_empty_support(
                edge_logits=edge_logits,
                edge_label=batch.edge_label,
                pos_weight=pos_weight,
            )
        else:
            loss_edge = batch.apo_pos.new_zeros(())
            this_edge_count = 0
        if args.lambda_ranking > 0:
            loss_ranking, this_ranking_count = edge_delta_ranking_loss(
                edge_scores=edge_logits,
                apo_pos=batch.apo_pos,
                holo_pos=batch.holo_pos,
                edge_index=batch.edge_index,
                margin_delta=args.ranking_margin_delta,
                margin_score=args.ranking_margin_score,
                max_pairs=args.ranking_max_pairs,
            )
        else:
            loss_ranking = edge_logits.new_zeros(())
            this_ranking_count = 0
        loss = (
            args.lambda_contrastive * loss_contrastive
            + args.lambda_edge * loss_edge
            + args.lambda_ranking * loss_ranking
            + args.lambda_pseudo * loss_pseudo
        )

        batch_size_graph = int(batch.num_graphs)
        total += batch_size_graph
        total_loss += float(loss.item()) * batch_size_graph
        total_contrastive += float(loss_contrastive.item()) * batch_size_graph
        total_edge += float(loss_edge.item()) * batch_size_graph
        total_ranking += float(loss_ranking.item()) * batch_size_graph
        total_pseudo += float(loss_pseudo.item()) * batch_size_graph
        contrastive_count += contrastive_m["contrastive_count"]
        if contrastive_m["contrastive_count"] > 0:
            total_contrastive_acc += contrastive_m["contrastive_acc"] * batch_size_graph
            total_contrastive_pos_sim += contrastive_m["contrastive_pos_sim"] * batch_size_graph
            total_contrastive_neg_per_anchor += contrastive_m["contrastive_neg_per_anchor"] * batch_size_graph
        ranking_count += this_ranking_count
        pseudo_count += pseudo_m["pseudo_count"]
        pseudo_pos += pseudo_m["pseudo_pos"]
        if pseudo_m["pseudo_count"] > 0:
            total_pseudo_acc += pseudo_m["pseudo_acc"] * batch_size_graph
            if pseudo_m["pseudo_auc"] == pseudo_m["pseudo_auc"]:
                total_pseudo_auc += pseudo_m["pseudo_auc"] * batch_size_graph
            total_opening_score += pseudo_m["opening_score"] * batch_size_graph

        if this_edge_count > 0:
            prob = torch.sigmoid(edge_logits)
            pred = (prob >= 0.5).long()
            label = batch.edge_label.long()
            correct += int((pred == label).sum().item())
            edge_count += int(label.numel())
            all_scores.append(prob.detach().cpu())
            all_labels.append(label.detach().cpu())

    if all_scores:
        scores = torch.cat(all_scores, dim=0)
        labels = torch.cat(all_labels, dim=0)
        auc = binary_auc_torch(labels, scores)
    else:
        auc = float("nan")

    metrics = {
        "loss": total_loss / max(1, total),
        "loss_contrastive": total_contrastive / max(1, total),
        "loss_edge": total_edge / max(1, total),
        "loss_ranking": total_ranking / max(1, total),
        "loss_pseudo": total_pseudo / max(1, total),
        "contrastive_count": float(contrastive_count),
        "contrastive_acc": total_contrastive_acc / max(1, total),
        "contrastive_pos_sim": total_contrastive_pos_sim / max(1, total),
        "contrastive_neg_per_anchor": total_contrastive_neg_per_anchor / max(1, total),
        "edge_acc": (correct / edge_count) if edge_count > 0 else float("nan"),
        "edge_auc": auc,
        "edge_count": float(edge_count),
        "ranking_count": float(ranking_count),
        "pseudo_count": float(pseudo_count),
        "pseudo_pos_frac": float(pseudo_pos / max(1.0, pseudo_count)),
        "pseudo_acc": total_pseudo_acc / max(1, total),
        "pseudo_auc": total_pseudo_auc / max(1, total),
        "opening_score": total_opening_score / max(1, total),
    }
    return metrics


def load_checkpoint_if_needed(
    model: EdgeGCLModel,
    optimizer: torch.optim.Optimizer,
    scaler: torch.cuda.amp.GradScaler | None,
    ckpt_path: Path,
    device: torch.device,
) -> Tuple[int, float]:
    ckpt = torch.load(ckpt_path, map_location=device)
    model.load_state_dict(ckpt["model"])
    optimizer.load_state_dict(ckpt["optimizer"])
    if scaler is not None and ckpt.get("scaler") is not None:
        scaler.load_state_dict(ckpt["scaler"])
    start_epoch = int(ckpt.get("epoch", 0)) + 1
    best_val = float(ckpt.get("best_val_loss", float("inf")))
    return start_epoch, best_val


def save_checkpoint(
    path: Path,
    model: EdgeGCLModel,
    optimizer: torch.optim.Optimizer,
    scaler: torch.cuda.amp.GradScaler | None,
    epoch: int,
    best_val_loss: float,
    args: argparse.Namespace,
) -> None:
    state = {
        "epoch": epoch,
        "best_val_loss": best_val_loss,
        "model": model.state_dict(),
        "pockmon_backbone": model.pockmon_backbone_state_dict(),
        "optimizer": optimizer.state_dict(),
        "scaler": scaler.state_dict() if scaler is not None else None,
        "args": vars(args),
    }
    torch.save(state, path)


def main() -> None:
    args = parse_args()
    save_dir = Path(args.save_dir)
    setup_logging(save_dir)
    set_seed(args.seed)

    device = select_device(args.device)
    logging.info("Device: %s", device)

    data_dir = Path(args.data_dir)
    files = list_pt_files(data_dir)
    if args.max_samples > 0:
        files = files[: args.max_samples]
    validate_graph_files(files, args.validate_first_n)
    n_total = len(files)
    if n_total < 2:
        raise ValueError(f"Need at least 2 samples for train/val split, got {n_total}")

    train_idx, val_idx = split_indices(n_total, args.val_ratio, args.seed)
    logging.info("Total samples: %d | train: %d | val: %d", n_total, len(train_idx), len(val_idx))

    dataset = PTGraphDataset(files)
    train_set = Subset(dataset, train_idx)
    val_set = Subset(dataset, val_idx)

    train_loader = DataLoader(
        train_set,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
        pin_memory=(device.type == "cuda"),
    )
    val_loader = DataLoader(
        val_set,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        pin_memory=(device.type == "cuda"),
    )

    model = build_model_from_args(args).to(device)
    optimizer = AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    scaler_obj = torch.cuda.amp.GradScaler(enabled=True) if (args.amp and device.type == "cuda") else None

    start_epoch = 1
    best_val_loss = float("inf")

    if args.resume:
        resume_path = Path(args.resume)
        if not resume_path.exists():
            raise FileNotFoundError(f"Resume checkpoint not found: {resume_path}")
        start_epoch, best_val_loss = load_checkpoint_if_needed(
            model=model,
            optimizer=optimizer,
            scaler=scaler_obj,
            ckpt_path=resume_path,
            device=device,
        )
        logging.info("Resumed from %s (start epoch %d)", resume_path, start_epoch)

    config_dump = {
        "args": vars(args),
        "device": str(device),
        "train_size": len(train_set),
        "val_size": len(val_set),
    }
    save_json(save_dir / "run_config.json", config_dump)

    history_path = save_dir / "history.jsonl"
    logging.info("Start training for %d epochs", args.epochs)
    train_start = time.time()

    for epoch in range(start_epoch, args.epochs + 1):
        t0 = time.time()
        train_m = train_one_epoch(
            model=model,
            loader=train_loader,
            optimizer=optimizer,
            scaler=scaler_obj,
            device=device,
            args=args,
        )
        val_m = evaluate(model=model, loader=val_loader, device=device, args=args)
        dt = time.time() - t0

        row = {
            "epoch": epoch,
            "seconds": dt,
            "train": train_m,
            "val": val_m,
        }
        with history_path.open("a", encoding="utf-8") as f:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")

        logging.info(
            (
                "Epoch %d | %.1fs | "
                "train loss %.4f (p %.4f, c %.4f, cacc %.4f, csim %.4f, e %.4f, r %.4f, pacc %.4f, p_auc %.4f, eacc %.4f) | "
                "val loss %.4f (p %.4f, c %.4f, cacc %.4f, csim %.4f, e %.4f, r %.4f, pacc %.4f, p_auc %.4f, eacc %.4f, e_auc %.4f)"
            ),
            epoch,
            dt,
            train_m["loss"],
            train_m["loss_pseudo"],
            train_m["loss_contrastive"],
            train_m["contrastive_acc"],
            train_m["contrastive_pos_sim"],
            train_m["loss_edge"],
            train_m["loss_ranking"],
            train_m["pseudo_acc"],
            train_m["pseudo_auc"],
            train_m["edge_acc"],
            val_m["loss"],
            val_m["loss_pseudo"],
            val_m["loss_contrastive"],
            val_m["contrastive_acc"],
            val_m["contrastive_pos_sim"],
            val_m["loss_edge"],
            val_m["loss_ranking"],
            val_m["pseudo_acc"],
            val_m["pseudo_auc"],
            val_m["edge_acc"],
            val_m["edge_auc"],
        )

        if epoch % args.save_every == 0:
            save_checkpoint(
                path=save_dir / f"epoch_{epoch}.pt",
                model=model,
                optimizer=optimizer,
                scaler=scaler_obj,
                epoch=epoch,
                best_val_loss=best_val_loss,
                args=args,
            )

        if val_m["loss"] < best_val_loss:
            best_val_loss = val_m["loss"]
            save_checkpoint(
                path=save_dir / "best.pt",
                model=model,
                optimizer=optimizer,
                scaler=scaler_obj,
                epoch=epoch,
                best_val_loss=best_val_loss,
                args=args,
            )

    total_time = time.time() - train_start
    logging.info("Training completed in %.1f sec (%.2f hours)", total_time, total_time / 3600.0)
    logging.info("Best val loss: %.6f", best_val_loss)


if __name__ == "__main__":
    main()
